### ISSUE TITLE
The header is not copied into Result and ExperimentResult

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1114]
### Informations

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Trying to access the header of a Result or ExperimentResult object leads to AttributeError.

The backends (both Aer and IBMQ) should copy the header straight from qobj into result. Qiskit should use that to construct the header of Result and ExperimentResult.

After that, we should also get rid of the `copy_qasm_from_qobj_into_result` function. That info is already available in the header.

**Comment by balewski** [comment]
Hi @ajavadia,
thanks for clarification - it makes sense. When can I start to use job.qobj() ?
At the moment it produces this error:
jobObj=job.qobj()
AttributeError: 'IBMQJobPreQobj' object has no attribute 'qobj'
Jan

**Comment by ajavadia** [comment]
@balewski this is not available yet. It needs to be addressed at the cloud API level, and then Terra will support it as well. Probably a few weeks.

**Comment by balewski** [comment]
Thanks for the clarification. 
So after the change to ver 0.6  there is no method which would tell me what sequence of gates was actually executed on the hardware? Then I'll wait w/ my experiments - I do not like to drive with eyes closed.
How will I know the job.qobj() was added?
Thanks
Jan

**Comment by ajavadia** [comment]
This is fixed now.

**Comment by balewski** [comment]
Hi,
I just run my code against ibmQX4 and still see jobObj=job.qobj() crashes.
Can you point me to documentation how to access 
ran_qc=jobRes.get_ran_qasm(circuit_name)
Thanks
Jan

- - - 
jobRes=job.result()
jobData=jobRes.get_data()
pprint(jobData)
print('Get circuit as executed on backend=%s'%(backendName))
jobObj=job.qobj()
- - - 

job done, :
{'counts': {'00000': 9,
            '00010': 103,
            '11101': 1,
            '11110': 6},
 'date': '2018-12-14T05:40:06.945Z',
 'time': 48.650851011276245}
Get circuit as executed on backend=ibmqx4
Traceback (most recent call last):
  File "./run_ticket1.py", line 133, in <module>
    jobObj=job.qobj()
AttributeError: 'IBMQJobPreQobj' object has no attribute 'qobj'

**Comment by ajavadia** [comment]
@balewski this issue was just about the job header, and that is working correctly.

The issue of getting `job.qobj()` so you can access a job's payload after submission is something we are working on. It may make it to the shortly coming release (0.7), but if not it will be in the next minor one (0.7.1).

I opened a new issue to track that: https://github.com/Qiskit/qiskit-terra/issues/1529
