### ISSUE TITLE
Gate parameters do not support mix of indexes and bits

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2369]
It is not possible to refer to a mix of indexes and bits in gate arguments:
```python
qr1 = QuantumRegister(1, 'q1')
qr2 = QuantumRegister(1, 'q2')
cr = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qr2, qr1, cr)

print('Qubit ordering:', circuit.qubits)
print('Classical bit ordering:', circuit.clbits)

circuit.h(1)
circuit.measure(1,[qr1[0],1])
```
```
QiskitError: "Type error handeling [(QuantumRegister(1, 'q1'), 0), 1] (<class 'list'>)"
```
While this works:
```python
circuit.measure(1,[0,1])
```

**Comment by ajavadia** [comment]
Can we fix the typo in the error message? handeling -> handling

**Comment by kdk** [comment]
Typo is fixed as part of #2414.

**Comment by TharrmashasthaPV** [comment]
Hi @1ucian0 . Just checking how the progress is on the issue. I thought I could give this a shot.

**Comment by 1ucian0** [comment]
Please go ahead @TharrmashasthaPV !

**Comment by TharrmashasthaPV** [comment]
Hi @1ucian0 . I think this issue is resolved and so should be closed.

**Comment by 1ucian0** [comment]
Could it be that is still an issue for `measure`? The example code raises:
`CircuitError: 'carg is not a Clbit'`

**Comment by TharrmashasthaPV** [comment]
Hi @1ucian0 . Maybe that is because there is a small error in the example code. In
```
circuit.measure(1,[qr1[0],1])
```
the second argument should be a classical register I suppose? It works fine if we have 
```
circuit.measure(1,[cr[0],1])
```
instead of the first.

**Comment by 1ucian0** [comment]
You are right! This is fixed by #3490! 

(just to let you know, issues can be closed automatically when a PR is merged if you write "Fixes #<issue-number>" in the body of the PR text [instead of "Fixes issue #<issue-number>"](https://github.com/Qiskit/qiskit-terra/pull/3490#issue-342402048))

**Comment by TharrmashasthaPV** [comment]
> You are right! This is fixed by #3490!
> 
> (just to let you know, issues can be closed automatically when a PR is merged if you write "Fixes #" in the body of the PR text [instead of "Fixes issue #"](https://github.com/Qiskit/qiskit-terra/pull/3490#issue-342402048))

Thanks for the information @1ucian0 .
