### ISSUE TITLE
Transpiler and execution error with 20qubit Tokyo machine

### ISSUE THREAD

**Issue by revilooliver** [Qiskit/qiskit-terra#2912]
### Information

- **Qiskit Terra version**: 'qiskit-terra': '0.8.2',
- **Python version**:3.7.3
- **Operating system**: Windows64

### What is the current behavior?
When I tried to run experiment on ibmq_20_tokyo, the transpiler is giving me following error:

E:\1.NCSU\ECE\lab\quantum_computing\anaconda\envs\Qiskitenv\lib\site-packages\qiskit\transpiler\coupling.py in _compute_distance_matrix(self)
    146         for idx in range(size):
    147             cmap[idx, np.fromiter(lengths[idx].keys(), dtype=int)] = np.fromiter(
--> 148                 lengths[idx].values(), dtype=int)
    149         self._dist_matrix = cmap
    150 

IndexError: index 19 is out of bounds for axis 1 with size 19

Also, the execution() function is giving me the same error as it invokes the transpiler function. 
### Steps to reproduce the problem

Here's the command I used for transpile.

coupling_map = device.configuration().coupling_map
trans_qc = transpile(Circuit, backend_properties = properties, coupling_map=coupling_map)

Here's the detailed coupling map.  I guess the device is returning incorrect information. Now the "tokyo" backend only has 19 active qubits, so maybe the device should provide coupling information for qubits 0~18 rather than 0~19? 
[[0, 1], [0, 5], [1, 0], [1, 2], [1, 6], [2, 1], [2, 6], [3, 8], [4, 8], [4, 9], [5, 0], [5, 6], [5, 10], [5, 11], [6, 1], [6, 2], [6, 5], [6, 10], [6, 11], [8, 3], [8, 4], [8, 9], [8, 12], [8, 13], [9, 4], [9, 8], [10, 5], [10, 6], [10, 11], [10, 15], [11, 5], [11, 6], [11, 10], [11, 12], [11, 16], [11, 17], [12, 8], [12, 11], [12, 13], [12, 16], [13, 8], [13, 12], [13, 14], [13, 18], [13, 19], [14, 13], [14, 18], [14, 19], [15, 10], [15, 16], [16, 11], [16, 12], [16, 15], [16, 17], [17, 11], [17, 16], [17, 18], [18, 13], [18, 14], [18, 17], [19, 13], [19, 14]]

**Comment by ajavadia** [comment]
what is the `Circuit`?

**Comment by revilooliver** [comment]
My experiment was using this 4-qubit phase estimation circuit:
    qr = QuantumRegister(4)
    cr = ClassicalRegister(4)
    circuitName="PhaseEstimationCircuit"
    peaCircuit = QuantumCircuit(qr, cr)

    # Apply PEA
    for i in range(4):
        peaCircuit.h(qr[i])
    peaCircuit.u1(11*pi, qr[0])
    peaCircuit.u1(11*pi/2, qr[1])
    peaCircuit.u1(11*pi/4, qr[2])
    peaCircuit.u1(11*pi/8, qr[3])
    peaCircuit.h(qr[0])

    peaCircuit.cu1(-pi/2, qr[0], qr[1])
    peaCircuit.cu1(-pi/4, qr[0], qr[2])
    peaCircuit.cu1(-pi/8, qr[0], qr[3])

    peaCircuit.measure(qr[0], cr[0])

    peaCircuit.h(qr[1])
    peaCircuit.cu1(-pi/2, qr[1], qr[2])
    peaCircuit.cu1(-pi/4, qr[1], qr[3])
    peaCircuit.measure(qr[1], cr[1])

    peaCircuit.h(qr[2])
    peaCircuit.cu1(-pi/2, qr[2], qr[3])
    peaCircuit.measure(qr[2], cr[2])

    peaCircuit.h(qr[3])
    peaCircuit.measure(qr[3], cr[3])


    trans_qc = transpile(peaCircuit, backend_properties = properties, coupling_map=coupling_map)

**Comment by revilooliver** [comment]
The other circuit also gives an error, for example this simple circuit with only one X gate:

    qr = QuantumRegister(1)
    cr = ClassicalRegister(1)
    circuitName="Test"
    Circuit = QuantumCircuit(qr, cr)
    Circuit.x(qr[0])
    Circuit.measure(qr, cr)
    trans_qc = transpile(Circuit, backend=device, backend_properties = properties)

It gives me the error:

E:\1.NCSU\ECE\lab\quantum_computing\anaconda\envs\Qiskitenv\lib\site-packages\qiskit\dagcircuit\dagcircuit.py in _check_wiremap_validity(self, wire_map, keymap, valmap)
    476                 raise DAGCircuitError("invalid wire mapping key %s" % kname)
    477             if v not in valmap:
--> 478                 raise DAGCircuitError("invalid wire mapping value %s" % vname)
    479             if type(k) is not type(v):
    480                 raise DAGCircuitError("inconsistent wire_map at (%s,%s)" %

DAGCircuitError: 'invalid wire mapping value q[19]'

**Comment by nonhermitian** [comment]
This should be resolved

**Comment by ajavadia** [comment]
Please reopen if not resolved. Tokyo should be showing as 20Q again.
