### ISSUE TITLE
ValueError thrown on plotting hinton state function

### ISSUE THREAD

**Issue by gunchamalik** [Qiskit/qiskit-terra#4815]
### Information

- **Qiskit Terra version**: 0.19.6
- **Python version**: 3.7.6
- **Operating system**: Mac OS 10.15.5

### What is the current behavior?
ValueError is thrown on plotting hinton state function.

### Steps to reproduce the problem
1. Execute a simple circuit and plot hinton function.
`from qiskit import *`
`from qiskit.visualization import plot_state_hinton`

`bell = QuantumCircuit(2, 2)`
`bell.h(0)`
`bell.cx(0, 1)`
`backend = BasicAer.get_backend('statevector_simulator') # the device to run on`
`result = execute(bell, backend).result()`
`psi  = result.get_statevector(bell)`
`plot_state_hinton(psi)`
2. ValueError is thrown and the hinton state plot is broken.
`---------------------------------------------------------------------------`
`ValueError                                Traceback (most recent call last)`
`<ipython-input-14-e73faf0b95dd> in <module>`
`     11 psi  = result.get_statevector(bell)`
`     12 `
`---> 13 plot_state_hinton(psi)`

`/opt/conda/lib/python3.7/site-packages/qiskit/visualization/state_visualization.py in plot_state_hinton(rho, title, figsize, ax_real, ax_imag)
    142         ax1.set_xticks(np.arange(0, lx+0.5, 1))
    143         ax1.set_yticks(np.arange(0, ly+0.5, 1))
--> 144         ax1.set_yticklabels(row_names, fontsize=14)
    145         ax1.set_xticklabels(column_names, fontsize=14, rotation=90)
    146         ax1.autoscale_view()`

`/opt/conda/lib/python3.7/site-packages/matplotlib/axes/_base.py in wrapper(self, *args, **kwargs)
     61 
     62         def wrapper(self, *args, **kwargs):
---> 63             return get_method(self)(*args, **kwargs)
     64 
     65         wrapper.__module__ = owner.__module__`

`/opt/conda/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    449                 "parameter will become keyword-only %(removal)s.",
    450                 name=name, obj_type=f"parameter of {func.__name__}()")
--> 451         return func(*args, **kwargs)
    452 
    453     return wrapper`

`/opt/conda/lib/python3.7/site-packages/matplotlib/axis.py in _set_ticklabels(self, labels, fontdict, minor, **kwargs)
   1791         if fontdict is not None:
   1792             kwargs.update(fontdict)
-> 1793         return self.set_ticklabels(labels, minor=minor, **kwargs)
   1794 
   1795     @cbook._make_keyword_only("3.2", "minor")`

`/opt/conda/lib/python3.7/site-packages/matplotlib/axis.py in set_ticklabels(self, ticklabels, minor, **kwargs)
   1713             if len(locator.locs) != len(ticklabels) and len(ticklabels) != 0:
     1714                 raise ValueError
-> 1715                     "The number of FixedLocator locations"
   1716                     f" ({len(locator.locs)}), usually from a call to"
   1717                     " set_ticks, does not match"`

`ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (4).`
<img width="496" alt="Hinton state plot error" src="https://user-images.githubusercontent.com/8434529/88626858-f626dc80-d0c8-11ea-8de6-3ef5296a9a6e.png">

### What is the expected behavior?
Hinton state should be plotted without any error
<img width="474" alt="Hinton state without error" src="https://user-images.githubusercontent.com/8434529/88626938-1f476d00-d0c9-11ea-8aaf-30b1d4071330.png">

**Comment by anto-pv** [comment]
No, I got the expected output. 
whether you run this in correct way ? Or may be due to errors ipython or something.. Try to update all and run it..

**Comment by RyotaroDoi** [comment]
Can I give it a shot?

**Comment by mtreinish** [comment]
This issue was introduced with the recent release of matplotlib 3.3.0 and has already been fixed by #4739 it just hasn't been released yet. In the meantime you can downgrade your matplotlib version to be < 3.3.0 to avoid the issue until the next terra release. Since this has already been fixed I'm going to close this issue, but please feel free to reopen it if I'm missing something.

**Comment by gunchamalik** [comment]
@mtreinish thx.

**Comment by Hirmay** [comment]
> This issue was introduced with the recent release of matplotlib 3.3.0 and has already been fixed by #4739 it just hasn't been released yet. In the meantime you can downgrade your matplotlib version to be < 3.3.0 to avoid the issue until the next terra release. Since this has already been fixed I'm going to close this issue, but please feel free to reopen it if I'm missing something.

I tried downgrading to 3.0.3, 3.2.2 and few more but still facing the same issue
