### ISSUE TITLE
Statevector probabilities hard to read due to floating point round-off not being truncated

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5748]
### What is the expected enhancement?

Make this look better

```
     ┌───┐                ░ ┌───┐
q_0: ┤ H ├───────■────────░─┤ H ├
     ├───┤       │        ░ ├───┤
q_1: ┤ H ├───────┼────────░─┤ H ├
     ├───┤       │        ░ ├───┤
q_2: ┤ H ├───────┼────■───░─┤ H ├
     ├───┤       │    │   ░ ├───┤
q_3: ┤ H ├───────┼────┼───░─┤ H ├
     ├───┤┌───┐┌─┴─┐┌─┴─┐ ░ ├───┤
q_4: ┤ X ├┤ H ├┤ X ├┤ X ├─░─┤ H ├
     └───┘└───┘└───┘└───┘ ░ └───┘
```

```python
state1 = Statevector.from_instruction(qc)
state1.probabilities_dict()
```

```python
{'00000': 7.346682186127706e-101,
 '00001': 7.32104559714962e-68,
 '00010': 1.2837126075007331e-132,
 '00011': 2.28525270977926e-101,
 '00100': 7.423942627505283e-68,
 '00101': 1.9857297664135327e-34,
 '00110': 2.930596358531519e-101,
 '00111': 1.126011222444164e-68,
 '01000': 4.2223078868201295e-135,
 '01001': 5.876772581965757e-101,
 '01010': 1.1180143255225429e-167,
 '01011': 6.296609471049651e-134,
 '01100': 1.0444260097016873e-100,
 '01101': 6.382308251020071e-68,
 '01110': 1.174073321045043e-135,
 '01111': 2.5938265396944425e-101,
 '10000': 1.3375690670228462e-67,
 '10001': 7.924345495110263e-35,
 '10010': 1.6679505911645335e-99,
 '10011': 1.1913527410433241e-67,
 '10100': 5.577060207443594e-34,
 '10101': 0.9999999999999984,
 '10110': 8.437378252404033e-67,
 '10111': 1.814210694026683e-34,
 '11000': 3.135566019384955e-102,
 '11001': 6.339536706583704e-68,
 '11010': 1.2918555057623183e-134,
 '11011': 1.9591961158023475e-100,
 '11100': 7.859891699955402e-68,
 '11101': 3.6284213880533455e-34,
 '11110': 1.731144288425601e-102,
 '11111': 5.787124113500698e-68}
```

**Comment by TheGupta2012** [comment]
Hey @nonhermitian 
Can I have a go at this issue?

**Comment by nonhermitian** [comment]
Sure go for it!

**Comment by TheGupta2012** [comment]
Hey @nonhermitian 
Got the error and it was just a simple rounding off error in the `QuantumState` module particularly 
`        return self._vector_to_dict(
            self.probabilities(qargs=qargs, decimals=decimals),
            self.dims(qargs),
            string_labels=True)`

The `decimals` argument was responsible for the number of digits we round off to and what I wanted to confirm once was that is a 10 digit precision sufficient if None is mentioned?

**Comment by nonhermitian** [comment]
By default I would drop everything < 1e-15 as those are all floating point zeros.

**Comment by TheGupta2012** [comment]
Hey @nonhermitian 
I tried to make a PR but since I updated the docs too, it fails on 1 of the lint tests. Was I not supposed to do that?

**Comment by Cryoris** [comment]
It looks like you forgot to run `black` on the files, that's why the linter fails 🙂

**Comment by TheGupta2012** [comment]
It's strange, I did run black on the file and the linter fails still. 😕

**Comment by jakelishman** [comment]
This is a very old issue, sorry, but I'm going to close it as "won't fix": I don't think that truncation of outputs is something we should be doing automatically because we don't have the context to know what the user cares about - we might be truncating important numerics. Even if not, this would be a breaking API change.  `probabilities_dict` takes a `decimals` argument to allow the user to manually specify truncation, and this can be used to produce the preferred neater output.
