### ISSUE TITLE
LHS circuit calibration lost when combining with another circuit

### ISSUE THREAD

**Issue by nathanearnestnoble** [Qiskit/qiskit-terra#5939]
### Information

- **Qiskit Terra version**:0.17.0
- **Python version**:3.9.1
- **Operating system**:macOS Catalina

### What is the current behavior?
Calibration information is lost when using "+"(extend) for a lhs calibrated circuit.

### Steps to reproduce the problem

from qiskit import QuantumCircuit
from qiskit.circuit.library import RZXGate
from qiskit.pulse import Schedule

qc_cal = QuantumCircuit(2)
qc_cal.rzx(0.5, 0, 1)
qc_cal.add_calibration(RZXGate, (0, 1), params=[0.5], schedule=Schedule())
# qc_cal = transpile(qc_cal,backend)
print(qc_cal.calibrations)

qc = QuantumCircuit(2)
qc.h(0)

new_circ_cal_on_lhs = qc_cal + qc
print(new_circ_cal_on_lhs.calibrations) #calibration information is lost

new_circ_cal_on_rhs = qc +qc_cal
print(new_circ_cal_on_rhs.calibrations) #calibration information is kept

### What is the expected behavior?
For the calibrations information to be maintained when making new circuit from "calibrated_circuit+uncalibrated_circuit" 

### Suggested solutions

Modify extend function to check and add calibrations from lhs circuit.

**Comment by taalexander** [comment]
Fixed by #5910

**Comment by nathanearnestnoble** [comment]
Hi @taalexander - this issue still exists even with #5910.   #5910 fixes calibrations that exist in the right hand circuit but not the left.  (The above code should confirm this)
