### ISSUE TITLE
RZXCalibrationBuilder QiskitError message and other related weird bugs

### ISSUE THREAD

**Issue by poig** [Qiskit/qiskit-terra#8587]
### Environment

- **Qiskit Terra version**: 0.21.1
- **Python version**: 3.10.4
- **Operating system**: ubuntu 20.04.4 LTS and windows 11

### What is happening?

https://github.com/Qiskit/qiskit-terra/blob/36c91add58a6649fd0788c2abc7a5a236e2e6098/qiskit/transpiler/passes/calibration/rzx_builder.py?plain=#L82-L83

- so the QiskitError message will let people misunderstand the issue if implemented in the old way.
- also other weird bugs.

### How can we reproduce the issue?

I found bug from the two way for insert the parameters from [release note](https://qiskit.org/documentation/release_notes.html#upgrade-notes)
First way it works if there is defaults available which is V1 Backends
```
from qiskit.transpiler.passes import RZXCalibrationBuilder
from qiskit.providers.fake_provider import FakeMumbai

backend = FakeMumbai()
inst_map = backend.defaults().instruction_schedule_map
channel_map = backend.configuration().qubit_channel_mapping
cal_pass = RZXCalibrationBuilder(
    instruction_schedule_map=inst_map,
    qubit_channel_mapping=channel_map,
)
```
but this won't work because `backend.drive_channel(bit)` will pop up the error(but some of the fake backends won't pop up the error)
```
from qiskit.transpiler.passes import RZXCalibrationBuilder
from qiskit.providers.fake_provider import FakeMumbaiV2

backend = FakeMumbaiV2()
inst_map = backend.instruction_schedule_map
channel_map = {bit: backend.drive_channel(bit) for bit in range(backend.num_qubits)}
cal_pass = RZXCalibrationBuilder(
    instruction_schedule_map=inst_map,
    qubit_channel_mapping=channel_map,
)


Output:

Input In [1], in <dictcomp>(.0)
      4 backend = FakeMumbaiV2()
      5 inst_map = backend.instruction_schedule_map
----> 6 channel_map = {bit: backend.drive_channel(bit) for bit in range(backend.num_qubits)}
      7 cal_pass = RZXCalibrationBuilder(
      8     instruction_schedule_map=inst_map,
      9     qubit_channel_mapping=channel_map,
     10 )

File ~/miniconda3/envs/womanium-test2/lib/python3.10/site-packages/qiskit/providers/backend.py:510, in BackendV2.drive_channel(self, qubit)
    497 def drive_channel(self, qubit: int):
    498     """Return the drive channel for the given qubit.
    499 
    500     This is required to be implemented if the backend supports Pulse
   (...)
    508             measurement mapping
    509     """
--> 510     raise NotImplementedError

NotImplementedError: 
```

### What should happen?

it should pop up the correct error message

### Any suggestions?

maybe should have a better error message or better check statement for it.

**Comment by patdenim** [comment]
Identical error when using Pulse efficient transpilation on different backends (here below with auckland) 
 Fails with error  "QiskitError: 'Calibrations can only be added to Pulse-enabled backends'" 
 when `PassManager([RZXCalibrationBuilderNoEcho(backend)]` executes.
 Even though backend.configuration().open_pulse is `True`  
fails when checking 
 ```
 if instruction_schedule_map is None or qubit_channel_mapping is None:
      raise QiskitError("Calibrations can only be added to Pulse-enabled backends") 
```
instruction map and qubit channel mapping return correct information
inst_map = backend.defaults().instruction_schedule_map
channel_map = backend.configuration().qubit_channel_mapping

**Comment by jakelishman** [comment]
@nkanazawa1989 or @wshanks: could you have a look at this?

**Comment by wshanks** [comment]
I can't reproduce the error in the example in the OP. It looks like it was addressed by @nkanazawa1989 in #8444.

@nkanazawa1989 also shifted RZXCalibrationBuilder code around recently in #8276, but from what I can tell passing it just a `backend` rather than an `instruction_schedule_map` and `qubit_channel_mapping` has not been correct syntax recently (@patdenim's example).

**Comment by poig** [comment]
It works with no error pops up with qiskit-terra 0.21.2, I guess the bug is already fixed in the latest version already, thank you.

**Comment by patdenim** [comment]
The error with PassManager([RZXCalibrationBuilderNoEcho(backend)] is still present to me 
I'm using version {'qiskit-terra': '0.21.2', 'qiskit-aer': '0.10.4', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.19.2', 'qiskit': '0.37.2', 'qiskit-nature': '0.4.4', 'qiskit-finance': '0.3.4', 'qiskit-optimization': '0.4.0', 'qiskit-machine-learning': '0.4.0'}
same error message using auckland ("Calibrations can only be added to Pulse-enabled backends")

**Comment by wshanks** [comment]
@patdenim Your example is not a valid use of `RZXCalibrationBuilder` because it requires an `InstructionScheduleMap`:

https://github.com/Qiskit/qiskit-terra/blob/fdb62bea1eac6822b96e8dcd2fe19e7aee10027e/qiskit/transpiler/passes/calibration/builders.py#L105-L127

I think the error message is misleading, though maybe it is helpful in a larger flow where those arguments can not be supplied.

The code has actually changed since the release though: 

https://github.com/Qiskit/qiskit-terra/blob/070b9e214718b413f3d2f1142ffdc07d1d750c91/qiskit/transpiler/passes/calibration/rzx_builder.py#L61-L92

Now your example will not give an immediate error but it will still run into a problem later when it tries to use the backend as an inst_map.

**Comment by patdenim** [comment]
@wshanks Ouch, my mistake. Was using a bad code RZXCalibrationBuilderNoEcho(backend) instead of RZXCalibrationBuilderNoEcho(instruction_schedule_map=inst_map, qubit_channel_mapping=channel_map)
Sorry again.  Thks
